# Site settings
title: empty catch blocks
header-img: img/home-bg.jpg
email: 
copyright_name: empty catch blocks
description: ""
baseurl: ""
url: "http://www.emptycatchblocks.net"
twitter_username: felsig_
github_username:  felsig
facebook_username:  
email_username:  

# Site override settings
header-img-enabled: false

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
